spring:
  datasource:
    username: postgres
    password: ''
    url: jdbc:postgresql://localhost:5432/paymybuddy

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
